
		/*******************************************************************************
		* This file was generated by UI Builder.
		* This file will be auto-generated each and everytime you save your project.
		* Do not hand edit this file.
		********************************************************************************/
	#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void chatting_room_view_onuib_view_create(uib_chatting_room_view_view_context*, Evas_Object*, void*);
void chatting_room_view_make_room_button_onclicked(uib_chatting_room_view_view_context*, Evas_Object*, void*);
void chatting_room_view_add_friend_button_onclicked(uib_chatting_room_view_view_context*, Evas_Object*, void*);
void chatting_room_view_main_button_onclicked(uib_chatting_room_view_view_context*, Evas_Object*, void*);
void chatting_room_view_chatting_room_button_onclicked(uib_chatting_room_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_chatting_room_view_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_chatting_room_view_view_context* vc = calloc(1, sizeof(uib_chatting_room_view_view_context));
	vc->parent = parent;
	vc->view_name = "chatting_room_view";
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler
	evas_object_smart_callback_add(vc->root_container, "uib,view,create", (Evas_Smart_Cb)chatting_room_view_onuib_view_create, vc);
	evas_object_smart_callback_add(vc->make_room_button, "clicked", (Evas_Smart_Cb)chatting_room_view_make_room_button_onclicked, vc);
	evas_object_smart_callback_add(vc->add_friend_button, "clicked", (Evas_Smart_Cb)chatting_room_view_add_friend_button_onclicked, vc);
	evas_object_smart_callback_add(vc->main_button, "clicked", (Evas_Smart_Cb)chatting_room_view_main_button_onclicked, vc);
	evas_object_smart_callback_add(vc->chatting_room_button, "clicked", (Evas_Smart_Cb)chatting_room_view_chatting_room_button_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_chatting_room_view_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_chatting_room_view_view_context* vc = (uib_chatting_room_view_view_context*)uib_app_manager->find_view_context("chatting_room_view");
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->list1) {
			vc->list1= elm_list_add(vc->grid1);
		}
		if(vc->list1) {
			elm_list_mode_set(vc->list1, (Elm_List_Mode)ELM_LIST_SCROLL);
			elm_list_select_mode_set(vc->list1, (Elm_Object_Select_Mode)ELM_OBJECT_SELECT_MODE_DEFAULT);
			elm_list_multi_select_set(vc->list1, EINA_FALSE);
			elm_list_horizontal_set(vc->list1, EINA_FALSE);
			elm_scroller_policy_set(vc->list1, (Elm_Scroller_Policy)ELM_SCROLLER_POLICY_AUTO, (Elm_Scroller_Policy)ELM_SCROLLER_POLICY_AUTO);
			evas_object_size_hint_align_set(vc->list1, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->list1, 1.0, 1.0);
			elm_object_disabled_set(vc->list1, EINA_FALSE);
		elm_list_go(vc->list1);
			evas_object_show(vc->list1);
		}
		if (!vc->make_room_button) {
			vc->make_room_button = elm_button_add(vc->grid1);
		}
		if (vc->make_room_button) {
			evas_object_size_hint_align_set(vc->make_room_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->make_room_button, 1.0, 1.0);			elm_object_text_set(vc->make_room_button,_UIB_LOCALE("Make Room"));
			elm_object_style_set(vc->make_room_button,"default");
			evas_object_show(vc->make_room_button);
		}
		if (!vc->add_friend_button) {
			vc->add_friend_button = elm_button_add(vc->grid1);
		}
		if (vc->add_friend_button) {
			evas_object_size_hint_align_set(vc->add_friend_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->add_friend_button, 1.0, 1.0);			elm_object_text_set(vc->add_friend_button,_UIB_LOCALE("Add Friend"));
			elm_object_style_set(vc->add_friend_button,"default");
			evas_object_show(vc->add_friend_button);
		}
		if (!vc->main_button) {
			vc->main_button = elm_button_add(vc->grid1);
		}
		if (vc->main_button) {
			evas_object_size_hint_align_set(vc->main_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->main_button, 1.0, 1.0);			elm_object_text_set(vc->main_button,_UIB_LOCALE("Main"));
			elm_object_style_set(vc->main_button,"default");
			evas_object_show(vc->main_button);
		}
		if (!vc->chatting_room_button) {
			vc->chatting_room_button = elm_button_add(vc->grid1);
		}
		if (vc->chatting_room_button) {
			evas_object_size_hint_align_set(vc->chatting_room_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->chatting_room_button, 1.0, 1.0);			elm_object_text_set(vc->chatting_room_button,_UIB_LOCALE("Room"));
			elm_object_style_set(vc->chatting_room_button,"default");
			evas_object_show(vc->chatting_room_button);
		}
		elm_grid_pack(vc->grid1, vc->list1, 56, 147, 879, 670);		elm_grid_pack(vc->grid1, vc->make_room_button, 342, 39, 300, 80);		elm_grid_pack(vc->grid1, vc->add_friend_button, 649, 875, 300, 100);		elm_grid_pack(vc->grid1, vc->main_button, 14, 875, 300, 100);		elm_grid_pack(vc->grid1, vc->chatting_room_button, 331, 875, 300, 100);		evas_object_show(vc->grid1);
	}
}

