
		/*******************************************************************************
		* This file was generated by UI Builder.
		* This file will be auto-generated each and everytime you save your project.
		* Do not hand edit this file.
		********************************************************************************/
	#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void add_friend_view_add_friend_search_button_onclicked(uib_add_friend_view_view_context*, Evas_Object*, void*);
void add_friend_view_add_friend_add_button_onclicked(uib_add_friend_view_view_context*, Evas_Object*, void*);
void add_friend_view_main_button_onclicked(uib_add_friend_view_view_context*, Evas_Object*, void*);
void add_friend_view_chatting_room_button_onclicked(uib_add_friend_view_view_context*, Evas_Object*, void*);
void add_friend_view_add_friend_button_onclicked(uib_add_friend_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_add_friend_view_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_add_friend_view_view_context* vc = calloc(1, sizeof(uib_add_friend_view_view_context));
	vc->parent = parent;
	vc->view_name = "add_friend_view";
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler
	evas_object_smart_callback_add(vc->add_friend_search_button, "clicked", (Evas_Smart_Cb)add_friend_view_add_friend_search_button_onclicked, vc);
	evas_object_smart_callback_add(vc->add_friend_add_button, "clicked", (Evas_Smart_Cb)add_friend_view_add_friend_add_button_onclicked, vc);
	evas_object_smart_callback_add(vc->main_button, "clicked", (Evas_Smart_Cb)add_friend_view_main_button_onclicked, vc);
	evas_object_smart_callback_add(vc->chatting_room_button, "clicked", (Evas_Smart_Cb)add_friend_view_chatting_room_button_onclicked, vc);
	evas_object_smart_callback_add(vc->add_friend_button, "clicked", (Evas_Smart_Cb)add_friend_view_add_friend_button_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_add_friend_view_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_add_friend_view_view_context* vc = (uib_add_friend_view_view_context*)uib_app_manager->find_view_context("add_friend_view");
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->logo_square) {
			vc->logo_square = elm_image_add(vc->grid1);
		}
		if(vc->logo_square) {
			elm_image_smooth_set(vc->logo_square, EINA_TRUE);
			elm_image_no_scale_set(vc->logo_square, EINA_FALSE);
			elm_image_resizable_set(vc->logo_square, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->logo_square, EINA_FALSE);
			elm_image_fill_outside_set(vc->logo_square, EINA_FALSE);
			elm_image_editable_set(vc->logo_square, EINA_FALSE);
			evas_object_size_hint_align_set(vc->logo_square, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->logo_square, 1.0, 1.0);
			evas_object_show(vc->logo_square);
		}
		if (!vc->add_friend_label) {
			vc->add_friend_label = elm_label_add(vc->grid1);
		}
		if(vc->add_friend_label) {
			evas_object_size_hint_align_set(vc->add_friend_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->add_friend_label, 1.0, 1.0);			elm_object_text_set(vc->add_friend_label,_UIB_LOCALE("ID"));
			elm_label_line_wrap_set(vc->add_friend_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->add_friend_label,0);
			elm_label_ellipsis_set(vc->add_friend_label, EINA_FALSE);
			evas_object_show(vc->add_friend_label);
		}
		if (!vc->add_friend_entry) {
			vc->add_friend_entry= elm_entry_add(vc->grid1);
		}
		if(vc->add_friend_entry) {
			elm_entry_single_line_set(vc->add_friend_entry, EINA_FALSE);
			elm_entry_password_set(vc->add_friend_entry, EINA_FALSE);
			elm_entry_editable_set(vc->add_friend_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->add_friend_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->add_friend_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->add_friend_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->add_friend_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->add_friend_entry, EINA_FALSE);
			evas_object_show(vc->add_friend_entry);
		}
		if (!vc->add_friend_search_button) {
			vc->add_friend_search_button = elm_button_add(vc->grid1);
		}
		if (vc->add_friend_search_button) {
			evas_object_size_hint_align_set(vc->add_friend_search_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->add_friend_search_button, 1.0, 1.0);			elm_object_text_set(vc->add_friend_search_button,_UIB_LOCALE("Search"));
			elm_object_style_set(vc->add_friend_search_button,"default");
			evas_object_show(vc->add_friend_search_button);
		}
		if (!vc->entry1) {
			vc->entry1= elm_entry_add(vc->grid1);
		}
		if(vc->entry1) {
			elm_object_text_set(vc->entry1,_UIB_LOCALE("Entry"));
			elm_entry_single_line_set(vc->entry1, EINA_FALSE);
			elm_entry_password_set(vc->entry1, EINA_FALSE);
			elm_entry_editable_set(vc->entry1, EINA_FALSE);
			elm_entry_context_menu_disabled_set(vc->entry1, EINA_FALSE);
			elm_entry_scrollable_set(vc->entry1, EINA_FALSE);
			evas_object_size_hint_align_set(vc->entry1, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->entry1, 1.0, 1.0);
			elm_object_disabled_set(vc->entry1, EINA_FALSE);
			evas_object_show(vc->entry1);
		}
		if (!vc->add_friend_add_button) {
			vc->add_friend_add_button = elm_button_add(vc->grid1);
		}
		if (vc->add_friend_add_button) {
			evas_object_size_hint_align_set(vc->add_friend_add_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->add_friend_add_button, 1.0, 1.0);			elm_object_text_set(vc->add_friend_add_button,_UIB_LOCALE("Add Friend"));
			elm_object_style_set(vc->add_friend_add_button,"default");
			evas_object_show(vc->add_friend_add_button);
		}
		if (!vc->main_button) {
			vc->main_button = elm_button_add(vc->grid1);
		}
		if (vc->main_button) {
			evas_object_size_hint_align_set(vc->main_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->main_button, 1.0, 1.0);			elm_object_text_set(vc->main_button,_UIB_LOCALE("Main"));
			elm_object_style_set(vc->main_button,"default");
			evas_object_show(vc->main_button);
		}
		if (!vc->chatting_room_button) {
			vc->chatting_room_button = elm_button_add(vc->grid1);
		}
		if (vc->chatting_room_button) {
			evas_object_size_hint_align_set(vc->chatting_room_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->chatting_room_button, 1.0, 1.0);			elm_object_text_set(vc->chatting_room_button,_UIB_LOCALE("Room"));
			elm_object_style_set(vc->chatting_room_button,"default");
			evas_object_show(vc->chatting_room_button);
		}
		if (!vc->add_friend_button) {
			vc->add_friend_button = elm_button_add(vc->grid1);
		}
		if (vc->add_friend_button) {
			evas_object_size_hint_align_set(vc->add_friend_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->add_friend_button, 1.0, 1.0);			elm_object_text_set(vc->add_friend_button,_UIB_LOCALE("Add"));
			elm_object_style_set(vc->add_friend_button,"default");
			evas_object_show(vc->add_friend_button);
		}
		elm_grid_pack(vc->grid1, vc->logo_square, 83, 49, 815, 321);		elm_grid_pack(vc->grid1, vc->add_friend_label, 83, 420, 200, 40);		elm_grid_pack(vc->grid1, vc->add_friend_entry, 349, 420, 330, 40);		elm_grid_pack(vc->grid1, vc->add_friend_search_button, 747, 420, 181, 40);		elm_grid_pack(vc->grid1, vc->entry1, 189, 545, 600, 55);		elm_grid_pack(vc->grid1, vc->add_friend_add_button, 276, 680, 414, 95);		elm_grid_pack(vc->grid1, vc->main_button, 14, 875, 300, 100);		elm_grid_pack(vc->grid1, vc->chatting_room_button, 331, 875, 300, 100);		elm_grid_pack(vc->grid1, vc->add_friend_button, 649, 875, 300, 100);		evas_object_show(vc->grid1);
	}
}

