
		/*******************************************************************************
		* This file was generated by UI Builder.
		* This file will be auto-generated each and everytime you save your project.
		* Do not hand edit this file.
		********************************************************************************/
	#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void signup_view_signup_id_check_button_onclicked(uib_signup_view_view_context*, Evas_Object*, void*);
void signup_view_signup_phone_check_button_onclicked(uib_signup_view_view_context*, Evas_Object*, void*);
void signup_view_signup_button_onclicked(uib_signup_view_view_context*, Evas_Object*, void*);
void signup_view_signup_pw_check_button_onclicked(uib_signup_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_signup_view_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_signup_view_view_context* vc = calloc(1, sizeof(uib_signup_view_view_context));
	vc->parent = parent;
	vc->view_name = "signup_view";
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler
	evas_object_smart_callback_add(vc->signup_id_check_button, "clicked", (Evas_Smart_Cb)signup_view_signup_id_check_button_onclicked, vc);
	evas_object_smart_callback_add(vc->signup_phone_check_button, "clicked", (Evas_Smart_Cb)signup_view_signup_phone_check_button_onclicked, vc);
	evas_object_smart_callback_add(vc->email_certify_button, "clicked", (Evas_Smart_Cb)signup_view_signup_button_onclicked, vc);
	evas_object_smart_callback_add(vc->signup_pw_check_button, "clicked", (Evas_Smart_Cb)signup_view_signup_pw_check_button_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_signup_view_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_signup_view_view_context* vc = (uib_signup_view_view_context*)uib_app_manager->find_view_context("signup_view");
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->logo_rectangle) {
			vc->logo_rectangle = elm_image_add(vc->grid1);
		}
		if(vc->logo_rectangle) {
			elm_image_smooth_set(vc->logo_rectangle, EINA_TRUE);
			elm_image_no_scale_set(vc->logo_rectangle, EINA_FALSE);
			elm_image_resizable_set(vc->logo_rectangle, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->logo_rectangle, EINA_FALSE);
			elm_image_fill_outside_set(vc->logo_rectangle, EINA_FALSE);
			elm_image_editable_set(vc->logo_rectangle, EINA_FALSE);
			evas_object_size_hint_align_set(vc->logo_rectangle, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->logo_rectangle, 1.0, 1.0);
			evas_object_show(vc->logo_rectangle);
		}
		if (!vc->signup_id_label) {
			vc->signup_id_label = elm_label_add(vc->grid1);
		}
		if(vc->signup_id_label) {
			evas_object_size_hint_align_set(vc->signup_id_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_id_label, 1.0, 1.0);			elm_object_text_set(vc->signup_id_label,_UIB_LOCALE("ID"));
			elm_label_line_wrap_set(vc->signup_id_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->signup_id_label,0);
			elm_label_ellipsis_set(vc->signup_id_label, EINA_FALSE);
			evas_object_show(vc->signup_id_label);
		}
		if (!vc->signup_pw_label) {
			vc->signup_pw_label = elm_label_add(vc->grid1);
		}
		if(vc->signup_pw_label) {
			evas_object_size_hint_align_set(vc->signup_pw_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_pw_label, 1.0, 1.0);			elm_object_text_set(vc->signup_pw_label,_UIB_LOCALE("PW"));
			elm_label_line_wrap_set(vc->signup_pw_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->signup_pw_label,0);
			elm_label_ellipsis_set(vc->signup_pw_label, EINA_FALSE);
			evas_object_show(vc->signup_pw_label);
		}
		if (!vc->signup_pw2_label) {
			vc->signup_pw2_label = elm_label_add(vc->grid1);
		}
		if(vc->signup_pw2_label) {
			evas_object_size_hint_align_set(vc->signup_pw2_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_pw2_label, 1.0, 1.0);			elm_object_text_set(vc->signup_pw2_label,_UIB_LOCALE("PW again"));
			elm_label_line_wrap_set(vc->signup_pw2_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->signup_pw2_label,0);
			elm_label_ellipsis_set(vc->signup_pw2_label, EINA_FALSE);
			evas_object_show(vc->signup_pw2_label);
		}
		if (!vc->signup_name_label) {
			vc->signup_name_label = elm_label_add(vc->grid1);
		}
		if(vc->signup_name_label) {
			evas_object_size_hint_align_set(vc->signup_name_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_name_label, 1.0, 1.0);			elm_object_text_set(vc->signup_name_label,_UIB_LOCALE("Name"));
			elm_label_line_wrap_set(vc->signup_name_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->signup_name_label,0);
			elm_label_ellipsis_set(vc->signup_name_label, EINA_FALSE);
			evas_object_show(vc->signup_name_label);
		}
		if (!vc->signup_phone_label) {
			vc->signup_phone_label = elm_label_add(vc->grid1);
		}
		if(vc->signup_phone_label) {
			evas_object_size_hint_align_set(vc->signup_phone_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_phone_label, 1.0, 1.0);			elm_object_text_set(vc->signup_phone_label,_UIB_LOCALE("Phone Number"));
			elm_label_line_wrap_set(vc->signup_phone_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->signup_phone_label,0);
			elm_label_ellipsis_set(vc->signup_phone_label, EINA_FALSE);
			evas_object_show(vc->signup_phone_label);
		}
		if (!vc->signup_id_entry) {
			vc->signup_id_entry= elm_entry_add(vc->grid1);
		}
		if(vc->signup_id_entry) {
			elm_entry_single_line_set(vc->signup_id_entry, EINA_FALSE);
			elm_entry_password_set(vc->signup_id_entry, EINA_FALSE);
			elm_entry_editable_set(vc->signup_id_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->signup_id_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->signup_id_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->signup_id_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->signup_id_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->signup_id_entry, EINA_FALSE);
			evas_object_show(vc->signup_id_entry);
		}
		if (!vc->signup_pw_entry) {
			vc->signup_pw_entry= elm_entry_add(vc->grid1);
		}
		if(vc->signup_pw_entry) {
			elm_entry_single_line_set(vc->signup_pw_entry, EINA_FALSE);
			elm_entry_password_set(vc->signup_pw_entry, EINA_TRUE);
			elm_entry_editable_set(vc->signup_pw_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->signup_pw_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->signup_pw_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->signup_pw_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->signup_pw_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->signup_pw_entry, EINA_FALSE);
			evas_object_show(vc->signup_pw_entry);
		}
		if (!vc->signup_pw2_entry) {
			vc->signup_pw2_entry= elm_entry_add(vc->grid1);
		}
		if(vc->signup_pw2_entry) {
			elm_entry_single_line_set(vc->signup_pw2_entry, EINA_FALSE);
			elm_entry_password_set(vc->signup_pw2_entry, EINA_TRUE);
			elm_entry_editable_set(vc->signup_pw2_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->signup_pw2_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->signup_pw2_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->signup_pw2_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->signup_pw2_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->signup_pw2_entry, EINA_FALSE);
			evas_object_show(vc->signup_pw2_entry);
		}
		if (!vc->signup_name_entry) {
			vc->signup_name_entry= elm_entry_add(vc->grid1);
		}
		if(vc->signup_name_entry) {
			elm_entry_single_line_set(vc->signup_name_entry, EINA_FALSE);
			elm_entry_password_set(vc->signup_name_entry, EINA_FALSE);
			elm_entry_editable_set(vc->signup_name_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->signup_name_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->signup_name_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->signup_name_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->signup_name_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->signup_name_entry, EINA_FALSE);
			evas_object_show(vc->signup_name_entry);
		}
		if (!vc->signup_phone_entry) {
			vc->signup_phone_entry= elm_entry_add(vc->grid1);
		}
		if(vc->signup_phone_entry) {
			elm_entry_single_line_set(vc->signup_phone_entry, EINA_FALSE);
			elm_entry_password_set(vc->signup_phone_entry, EINA_FALSE);
			elm_entry_editable_set(vc->signup_phone_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->signup_phone_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->signup_phone_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->signup_phone_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->signup_phone_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->signup_phone_entry, EINA_FALSE);
			evas_object_show(vc->signup_phone_entry);
		}
		if (!vc->signup_id_check_button) {
			vc->signup_id_check_button = elm_button_add(vc->grid1);
		}
		if (vc->signup_id_check_button) {
			evas_object_size_hint_align_set(vc->signup_id_check_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_id_check_button, 1.0, 1.0);			elm_object_text_set(vc->signup_id_check_button,_UIB_LOCALE("Check"));
			elm_object_style_set(vc->signup_id_check_button,"default");
			evas_object_show(vc->signup_id_check_button);
		}
		if (!vc->signup_phone_check_button) {
			vc->signup_phone_check_button = elm_button_add(vc->grid1);
		}
		if (vc->signup_phone_check_button) {
			evas_object_size_hint_align_set(vc->signup_phone_check_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_phone_check_button, 1.0, 1.0);			elm_object_text_set(vc->signup_phone_check_button,_UIB_LOCALE("Check"));
			elm_object_style_set(vc->signup_phone_check_button,"default");
			evas_object_show(vc->signup_phone_check_button);
		}
		if (!vc->email_certify_button) {
			vc->email_certify_button = elm_button_add(vc->grid1);
		}
		if (vc->email_certify_button) {
			evas_object_size_hint_align_set(vc->email_certify_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->email_certify_button, 1.0, 1.0);			elm_object_text_set(vc->email_certify_button,_UIB_LOCALE("Email-certify"));
			elm_object_style_set(vc->email_certify_button,"default");
			evas_object_show(vc->email_certify_button);
		}
		if (!vc->signup_pw_check_button) {
			vc->signup_pw_check_button = elm_button_add(vc->grid1);
		}
		if (vc->signup_pw_check_button) {
			evas_object_size_hint_align_set(vc->signup_pw_check_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->signup_pw_check_button, 1.0, 1.0);			elm_object_text_set(vc->signup_pw_check_button,_UIB_LOCALE("Check"));
			elm_object_style_set(vc->signup_pw_check_button,"default");
			evas_object_show(vc->signup_pw_check_button);
		}
		elm_grid_pack(vc->grid1, vc->logo_rectangle, 83, 49, 815, 321);		elm_grid_pack(vc->grid1, vc->signup_id_label, 65, 400, 204, 40);		elm_grid_pack(vc->grid1, vc->signup_pw_label, 65, 470, 204, 40);		elm_grid_pack(vc->grid1, vc->signup_pw2_label, 65, 540, 204, 40);		elm_grid_pack(vc->grid1, vc->signup_name_label, 65, 610, 204, 40);		elm_grid_pack(vc->grid1, vc->signup_phone_label, 65, 680, 204, 40);		elm_grid_pack(vc->grid1, vc->signup_id_entry, 332, 400, 419, 40);		elm_grid_pack(vc->grid1, vc->signup_pw_entry, 332, 470, 419, 40);		elm_grid_pack(vc->grid1, vc->signup_pw2_entry, 332, 540, 419, 40);		elm_grid_pack(vc->grid1, vc->signup_name_entry, 332, 610, 419, 40);		elm_grid_pack(vc->grid1, vc->signup_phone_entry, 332, 680, 419, 40);		elm_grid_pack(vc->grid1, vc->signup_id_check_button, 781, 400, 182, 40);		elm_grid_pack(vc->grid1, vc->signup_phone_check_button, 780, 680, 182, 40);		elm_grid_pack(vc->grid1, vc->email_certify_button, 304, 770, 370, 68);		elm_grid_pack(vc->grid1, vc->signup_pw_check_button, 781, 540, 182, 40);		evas_object_show(vc->grid1);
	}
}

