
		/*******************************************************************************
		* This file was generated by UI Builder.
		* This file will be auto-generated each and everytime you save your project.
		* Do not hand edit this file.
		********************************************************************************/
	#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void pw_find_view_pw_find_button_onclicked(uib_pw_find_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_pw_find_view_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_pw_find_view_view_context* vc = calloc(1, sizeof(uib_pw_find_view_view_context));
	vc->parent = parent;
	vc->view_name = "pw_find_view";
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler
	evas_object_smart_callback_add(vc->pw_find_button, "clicked", (Evas_Smart_Cb)pw_find_view_pw_find_button_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_pw_find_view_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_pw_find_view_view_context* vc = (uib_pw_find_view_view_context*)uib_app_manager->find_view_context("pw_find_view");
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->logo_square) {
			vc->logo_square = elm_image_add(vc->grid1);
		}
		if(vc->logo_square) {
			elm_image_smooth_set(vc->logo_square, EINA_TRUE);
			elm_image_no_scale_set(vc->logo_square, EINA_FALSE);
			elm_image_resizable_set(vc->logo_square, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->logo_square, EINA_FALSE);
			elm_image_fill_outside_set(vc->logo_square, EINA_FALSE);
			elm_image_editable_set(vc->logo_square, EINA_FALSE);
			evas_object_size_hint_align_set(vc->logo_square, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->logo_square, 1.0, 1.0);
			evas_object_show(vc->logo_square);
		}
		if (!vc->pw_find_id_entry) {
			vc->pw_find_id_entry= elm_entry_add(vc->grid1);
		}
		if(vc->pw_find_id_entry) {
			elm_entry_single_line_set(vc->pw_find_id_entry, EINA_FALSE);
			elm_entry_password_set(vc->pw_find_id_entry, EINA_FALSE);
			elm_entry_editable_set(vc->pw_find_id_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->pw_find_id_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->pw_find_id_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->pw_find_id_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->pw_find_id_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->pw_find_id_entry, EINA_FALSE);
			evas_object_show(vc->pw_find_id_entry);
		}
		if (!vc->pw_find_id_label) {
			vc->pw_find_id_label = elm_label_add(vc->grid1);
		}
		if(vc->pw_find_id_label) {
			evas_object_size_hint_align_set(vc->pw_find_id_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->pw_find_id_label, 1.0, 1.0);			elm_object_text_set(vc->pw_find_id_label,_UIB_LOCALE("ID"));
			elm_label_line_wrap_set(vc->pw_find_id_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->pw_find_id_label,0);
			elm_label_ellipsis_set(vc->pw_find_id_label, EINA_FALSE);
			evas_object_show(vc->pw_find_id_label);
		}
		if (!vc->pw_find_name_entry) {
			vc->pw_find_name_entry= elm_entry_add(vc->grid1);
		}
		if(vc->pw_find_name_entry) {
			elm_entry_single_line_set(vc->pw_find_name_entry, EINA_FALSE);
			elm_entry_password_set(vc->pw_find_name_entry, EINA_FALSE);
			elm_entry_editable_set(vc->pw_find_name_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->pw_find_name_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->pw_find_name_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->pw_find_name_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->pw_find_name_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->pw_find_name_entry, EINA_FALSE);
			evas_object_show(vc->pw_find_name_entry);
		}
		if (!vc->pw_find_name_label) {
			vc->pw_find_name_label = elm_label_add(vc->grid1);
		}
		if(vc->pw_find_name_label) {
			evas_object_size_hint_align_set(vc->pw_find_name_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->pw_find_name_label, 1.0, 1.0);			elm_object_text_set(vc->pw_find_name_label,_UIB_LOCALE("Name"));
			elm_label_line_wrap_set(vc->pw_find_name_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->pw_find_name_label,0);
			elm_label_ellipsis_set(vc->pw_find_name_label, EINA_FALSE);
			evas_object_show(vc->pw_find_name_label);
		}
		if (!vc->pw_find_quiz_entry) {
			vc->pw_find_quiz_entry= elm_entry_add(vc->grid1);
		}
		if(vc->pw_find_quiz_entry) {
			elm_object_text_set(vc->pw_find_quiz_entry,_UIB_LOCALE("what is your mother`s name?"));
			elm_entry_single_line_set(vc->pw_find_quiz_entry, EINA_FALSE);
			elm_entry_password_set(vc->pw_find_quiz_entry, EINA_FALSE);
			elm_entry_editable_set(vc->pw_find_quiz_entry, EINA_FALSE);
			elm_entry_context_menu_disabled_set(vc->pw_find_quiz_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->pw_find_quiz_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->pw_find_quiz_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->pw_find_quiz_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->pw_find_quiz_entry, EINA_FALSE);
			evas_object_show(vc->pw_find_quiz_entry);
		}
		if (!vc->pw_find_quiz_label) {
			vc->pw_find_quiz_label = elm_label_add(vc->grid1);
		}
		if(vc->pw_find_quiz_label) {
			evas_object_size_hint_align_set(vc->pw_find_quiz_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->pw_find_quiz_label, 1.0, 1.0);			elm_object_text_set(vc->pw_find_quiz_label,_UIB_LOCALE("Quiz"));
			elm_label_line_wrap_set(vc->pw_find_quiz_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->pw_find_quiz_label,0);
			elm_label_ellipsis_set(vc->pw_find_quiz_label, EINA_FALSE);
			evas_object_show(vc->pw_find_quiz_label);
		}
		if (!vc->pw_find_answer_entry) {
			vc->pw_find_answer_entry= elm_entry_add(vc->grid1);
		}
		if(vc->pw_find_answer_entry) {
			elm_entry_single_line_set(vc->pw_find_answer_entry, EINA_FALSE);
			elm_entry_password_set(vc->pw_find_answer_entry, EINA_FALSE);
			elm_entry_editable_set(vc->pw_find_answer_entry, EINA_TRUE);
			elm_entry_context_menu_disabled_set(vc->pw_find_answer_entry, EINA_FALSE);
			elm_entry_scrollable_set(vc->pw_find_answer_entry, EINA_FALSE);
			evas_object_size_hint_align_set(vc->pw_find_answer_entry, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->pw_find_answer_entry, 1.0, 1.0);
			elm_object_disabled_set(vc->pw_find_answer_entry, EINA_FALSE);
			evas_object_show(vc->pw_find_answer_entry);
		}
		if (!vc->pw_find_answer_label) {
			vc->pw_find_answer_label = elm_label_add(vc->grid1);
		}
		if(vc->pw_find_answer_label) {
			evas_object_size_hint_align_set(vc->pw_find_answer_label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->pw_find_answer_label, 1.0, 1.0);			elm_object_text_set(vc->pw_find_answer_label,_UIB_LOCALE("Answer"));
			elm_label_line_wrap_set(vc->pw_find_answer_label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->pw_find_answer_label,0);
			elm_label_ellipsis_set(vc->pw_find_answer_label, EINA_FALSE);
			evas_object_show(vc->pw_find_answer_label);
		}
		if (!vc->pw_find_button) {
			vc->pw_find_button = elm_button_add(vc->grid1);
		}
		if (vc->pw_find_button) {
			evas_object_size_hint_align_set(vc->pw_find_button, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->pw_find_button, 1.0, 1.0);			elm_object_text_set(vc->pw_find_button,_UIB_LOCALE("Find Password"));
			elm_object_style_set(vc->pw_find_button,"default");
			evas_object_show(vc->pw_find_button);
		}
		elm_grid_pack(vc->grid1, vc->logo_square, 83, 49, 815, 321);		elm_grid_pack(vc->grid1, vc->pw_find_id_entry, 350, 420, 420, 40);		elm_grid_pack(vc->grid1, vc->pw_find_id_label, 83, 420, 200, 40);		elm_grid_pack(vc->grid1, vc->pw_find_name_entry, 350, 500, 420, 40);		elm_grid_pack(vc->grid1, vc->pw_find_name_label, 83, 500, 200, 40);		elm_grid_pack(vc->grid1, vc->pw_find_quiz_entry, 350, 580, 420, 40);		elm_grid_pack(vc->grid1, vc->pw_find_quiz_label, 83, 580, 200, 40);		elm_grid_pack(vc->grid1, vc->pw_find_answer_entry, 350, 660, 420, 40);		elm_grid_pack(vc->grid1, vc->pw_find_answer_label, 83, 660, 200, 40);		elm_grid_pack(vc->grid1, vc->pw_find_button, 229, 778, 529, 75);		evas_object_show(vc->grid1);
	}
}

