
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
				
#ifndef UIB_PW_SETTING_VIEW_VIEW_H_
#define UIB_PW_SETTING_VIEW_VIEW_H_


#include "g_inc_uib.h"
#include "uib_views.h"

/**
* view context definitions
*/
		
typedef struct _uib_pw_setting_view_view_context {

	/* parent evas_object which was parameter of create function */
	Evas_Object *parent;
	/* root container UI Component of this view */
	Evas_Object *root_container;
	/* view class name */
	const char *view_name;
	/* control context to control this view */
	struct _uib_pw_setting_view_control_context *cc;

	/* UI Components in this view */
	Evas_Object *grid1;
	Evas_Object *logo_square;
	Evas_Object *pw_setting_id_entry;
	Evas_Object *pw_setting_id_label;
	Evas_Object *pw_setting_pw_entry;
	Evas_Object *pw_setting_pw_label;
	Evas_Object *pw_setting_pw2_entry;
	Evas_Object *pw_setting_pw2_label;
	Evas_Object *pw_setting_check_button;
	Evas_Object *pw_setting_button;
	Evas_Object *pw_setting_name_entry;
	Evas_Object *pw_setting_name_label;
} uib_pw_setting_view_view_context;


	
/**
* @brief	Create a new view then return view context of that view.
* 			You can delete view using evas_object_del(vc->evas_object) like other EFL evas objects.
*/
uib_view_context *uib_view_pw_setting_view_create(Evas_Object *parent, void *create_callback_param);
uib_view_context *uib_view_pw_setting_view_destroy(Evas_Object *parent, void *create_callback_param);

void uib_pw_setting_view_config_HD_portrait();
#endif /* UIB_PW_SETTING_VIEW_VIEW_H_ */
