
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef UIB_VIEWS_INC_H_
#define UIB_VIEWS_INC_H_

#include "uib_view1_view.h"
#include "uib_signup_view_view.h"
#include "uib_id_find_view_view.h"
#include "uib_pw_find_view_view.h"
#include "uib_pw_setting_view_view.h"
#include "uib_main_view_view.h"
#include "uib_add_friend_view_view.h"
#include "uib_chatting_room_view_view.h"
#include "uib_email_certify_view_view.h"
#include "uib_chatting_view_view.h"

#endif /* UIB_VIEWS_INC_H_ */
