/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"

#include "function.h"
#include "message_handler.h"
#include "define.h"


	char id[33];
	char password[33];
	char password2[33];
	char name[33];
	char phone_num[33];
	char buffer[257]={0,};
	int id_ok=0;
	int pw_ok=0;
	int phone_ok=0;

typedef struct _uib_signup_view_control_context {
	/* add your variables here */

} uib_signup_view_control_context;

void signup_view_signup_id_check_button_onclicked(uib_signup_view_view_context *vc, Evas_Object *obj, void *event_info) {

	//비교하여서 DB에 해당 아이디가 존재한다면
	if(1){
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Pass");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 1.0);
		strcpy(id,elm_entry_entry_get(vc->signup_id_entry));
		id_ok=1;
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Id Duplication");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void signup_view_signup_pw_check_button_onclicked(uib_signup_view_view_context *vc, Evas_Object *obj, void *event_info) {
	strcpy(password,elm_entry_entry_get(vc->signup_pw_entry));
	strcpy(password2,elm_entry_entry_get(vc->signup_pw2_entry));
	//pw엔트리와 pw2엔트리의 문자열이 다르면
	if(!strcmp(password,password2)){
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Pass");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 1.0);
		strcpy(password,elm_entry_entry_get(vc->signup_pw_entry));
		pw_ok=1;
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "PassWord Mismatch");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

void signup_view_signup_phone_check_button_onclicked(uib_signup_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//비교하여서 DB에 핸드폰 번호가 존재한다면
	if(1){
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Pass");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 1.0);
		strcpy(phone_num,elm_entry_entry_get(vc->signup_phone_entry));
		phone_ok=1;
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Phone Num Duplication");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

void signup_view_signup_button_onclicked(uib_signup_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//비교하여서 DB에 해당 아이디가 존재한다면
	if(id_ok==1&&pw_ok==1&&phone_ok==1){
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Regist Complete");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 1.0);
		strcpy(name,elm_entry_entry_get(vc->signup_name_entry));

		memcpy(buffer,id,32);
		memcpy(buffer+32,password,32);
		memcpy(buffer+64,name,32);
		memcpy(buffer+96,phone_num,32);
		sendMessage(2,NULL,my_sock_info,NULL,buffer);

		uib_util_push_view("email_certify_view");

	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Error");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}


