/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"

	char id[32];
	char password[32];
	char password2[32];
	char name[32];
	int pw2_ok = 0;

typedef struct _uib_pw_setting_view_control_context {
	/* add your variables here */

} uib_pw_setting_view_control_context;

void pw_setting_view_pw_setting_check_button_onclicked(uib_pw_setting_view_view_context *vc, Evas_Object *obj, void *event_info) {
	strcpy(password,elm_entry_entry_get(vc->pw_setting_pw_entry));
	strcpy(password2,elm_entry_entry_get(vc->pw_setting_pw2_entry));
	//pw엔트리와 pw2엔트리의 문자열이 다르면
	if(!strcmp(password,password2)){
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Pass");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 1.0);
		pw2_ok=1;
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "PassWord Mismatch");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

void pw_setting_view_pw_setting_button_onclicked(uib_pw_setting_view_view_context *vc, Evas_Object *obj, void *event_info) {
	if(pw2_ok==1){
		uib_util_push_view("main_view");
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Sign-Up Error");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

