/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"

#include "function.h"
#include "message_handler.h"
#include "define.h"

char friend_id[33];

typedef struct _uib_add_friend_view_control_context {
	/* add your variables here */

} uib_add_friend_view_control_context;

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void add_friend_view_add_friend_search_button_onclicked(uib_add_friend_view_view_context *vc, Evas_Object *obj, void *event_info) {

}

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void add_friend_view_add_friend_add_button_onclicked(uib_add_friend_view_view_context *vc, Evas_Object *obj, void *event_info) {
	strcpy(friend_id,elm_entry_entry_get(vc->add_friend_entry));
	sendMessage(5,my_index,0,0,friend_id);


	if(msg_recv.etc == 0){
		uib_util_push_view("main_view");
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Add Friend Fail");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void add_friend_view_main_button_onclicked(uib_add_friend_view_view_context *vc, Evas_Object *obj, void *event_info) {
	obj = uib_views_get_instance()->get_window_obj()->app_naviframe;
	elm_naviframe_item_pop(obj);
}

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void add_friend_view_chatting_room_button_onclicked(uib_add_friend_view_view_context *vc, Evas_Object *obj, void *event_info) {
	obj = uib_views_get_instance()->get_window_obj()->app_naviframe;
	elm_naviframe_item_pop(obj);
	uib_util_push_view("chatting_room_view");
}

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void add_friend_view_add_friend_button_onclicked(uib_add_friend_view_view_context *vc, Evas_Object *obj, void *event_info) {
	uib_views_get_instance()->uib_views_current_view_redraw();
}

