/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"

	char id[32];
	char phone_num[32];

typedef struct _uib_id_find_view_control_context {
	/* add your variables here */

} uib_id_find_view_control_context;

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void id_find_view_id_find_button_onclicked(uib_id_find_view_view_context *vc, Evas_Object *obj, void *event_info) {

	//엔트리에 입력된 아이디와 핸드폰번호를 DB에서 비교하여 일치한다면 아이디 제공
	if(1){
		strcpy(id,elm_entry_entry_get(vc->id_find_id_entry));
		strcpy(phone_num,elm_entry_entry_get(vc->id_find_phone_entry));
		Evas_Object *popup=elm_popup_add(vc->grid1);
		char temp[32]="id: ";
		strcat(temp,id);
		elm_object_text_set(popup, temp);
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 1.0);
		vc=NULL;
		uib_util_push_view("main_view");

	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "ID Find Error");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

