/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "function.h"
#include "message_handler.h"
#include "define.h"

	char id[32];
	char password[32];
	char buffer[65];

 typedef struct _uib_view1_control_context {

} uib_view1_control_context;


void view1_login_button_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {

	strcpy(id,elm_entry_entry_get(vc->id_entry));
	strcpy(password,elm_entry_entry_get(vc->pw_entry));
	memcpy(buffer,id,32);
	memcpy(buffer+32,password,32);

	sendMessage(3,-1,my_sock_info,-1,buffer);
	sem_wait(&sem_login);
	sendMessage(4,my_index,0,0,NULL);
	sem_wait(&sem_friend_list);
	sem_wait(&sem_room_list);

	if(my_index != -1){
		uib_util_push_view("main_view");
	}else{
		Evas_Object *popup=elm_popup_add(vc->grid1);
		elm_object_text_set(popup, "Id or PassWord Error");
		evas_object_show(popup);
		elm_popup_timeout_set(popup, 2.0);
	}
}

void view1_id_search_button_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	uib_util_push_view("id_find_view");

}

void view1_pw_search_button_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	uib_util_push_view("pw_find_view");
}

void view1_signup_button_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	uib_util_push_view("signup_view");
}

