/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"


void chatting_view_onuib_view_create(uib_chatting_view_view_context *vc, Evas_Object *obj, void *event_info) {

}
